###
GET http://localhost:8080/categories

###
POST http://localhost:8080/categories
Content-Type: application/json

{
  "name": "Streaming"
}

###
GET http://localhost:8080/categories/5

###
POST http://localhost:8080/people
Content-Type: application/json

{
  "name": "Streaming",
  "active": false,
  "publicPlace": "publicPlace",
  "number": "123",
  "complement": "complement",
  "cep": "cep",
  "district": "district",
  "city": "city",
  "state": "state"
}


###
GET http://localhost:8080/people

