### GET ALL CATEGORIES
GET {{host}}/api/v1/categories

### SAVE CATEGORY
POST {{host}}/api/v1/categories
Content-Type: application/json

{
  "name": "Workout"
}

### GET CATEGORY BY ID
GET {{host}}/api/v1/categories/5

### SAVE PERSON
POST {{host}}/api/v1/person
Content-Type: application/json

{
  "name": "Streaming",
  "active": false,
  "address": {
    "number": "123",
    "complement": "complement",
    "cep": "cep",
    "district": "district",
    "city": "city",
    "state": "state",
    "public_place": "state"
  }
}

### UPDATE PERSON
PUT {{host}}/api/v1/person/5
Content-Type: application/json

{
  "name": "Manuel Ernesto",
  "active": true,
  "address": {
    "number": "S/N",
    "complement": "Junto ao paparoka",
    "cep": "S/C",
    "district": "Mainga",
    "city": "Luanda",
    "state": "Luanda",
    "public_place": "Luanda"
  }
}

### UPDATE PERSON STATUS
PUT {{host}}/api/v1/person/5/active
Content-Type: application/json

true

### UPDATE PERSON Address
PUT {{host}}/api/v1/person/5/address
Content-Type: application/json

{
    "number": "123",
    "complement": "complement",
    "cep": "cep",
    "district": "district",
    "city": "city",
    "state": "state",
    "public_place": "state"
  }


### GET PERSON BY ID
GET {{host}}/api/v1/person/5

### GET ALL PEOPLE
GET {{host}}/api/v1/person/

### DELETE PERSON
DELETE {{host}}/api/v1/person/100